substitutions:
  name: seplos-bms
  battery_bank0: "${name} bank 0"
  battery_bank1: "${name} bank 1"
  battery_bank2: "${name} bank 2"
  external_components_source: github://syssi/esphome-seplos-bms@main
  tx_pin: GPIO4
  rx_pin: GPIO5

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
logger:

uart:
  id: uart0
  baud_rate: 9600
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  rx_buffer_size: 384

seplos_modbus:
  id: modbus0
  uart_id: uart0

seplos_bms:
  - id: battery_bank0
    address: 0x00
    seplos_modbus_id: modbus0
  - id: battery_bank1
    address: 0x01
    seplos_modbus_id: modbus0
  - id: battery_bank2
    address: 0x02
    seplos_modbus_id: modbus0

sensor:
  - platform: seplos_bms
    seplos_bms_id: battery_bank0
    min_cell_voltage:
      name: "${battery_bank0} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank0} max cell voltage"
    delta_cell_voltage:
      name: "${battery_bank0} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank0} average cell voltage"
    total_voltage:
      name: "${battery_bank0} total voltage"
    current:
      name: "${battery_bank0} current"
    power:
      name: "${battery_bank0} power"
    state_of_charge:
      name: "${battery_bank0} state of charge"

  - platform: seplos_bms
    seplos_bms_id: battery_bank1
    min_cell_voltage:
      name: "${battery_bank1} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank1} max cell voltage"
    delta_cell_voltage:
      name: "${battery_bank1} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank1} average cell voltage"
    total_voltage:
      name: "${battery_bank1} total voltage"
    current:
      name: "${battery_bank1} current"
    power:
      name: "${battery_bank1} power"
    state_of_charge:
      name: "${battery_bank1} state of charge"

  - platform: seplos_bms
    seplos_bms_id: battery_bank2
    min_cell_voltage:
      name: "${battery_bank2} min cell voltage"
    max_cell_voltage:
      name: "${battery_bank2} max cell voltage"
    delta_cell_voltage:
      name: "${battery_bank2} delta cell voltage"
    average_cell_voltage:
      name: "${battery_bank2} average cell voltage"
    total_voltage:
      name: "${battery_bank2} total voltage"
    current:
      name: "${battery_bank2} current"
    power:
      name: "${battery_bank2} power"
    state_of_charge:
      name: "${battery_bank2} state of charge"
